# Generated by Django 3.2.9 on 2021-11-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura_relogio', models.DateField()),
                ('numero_leitura', models.IntegerField()),
                ('kw', models.IntegerField()),
                ('valor', models.FloatField()),
                ('data_pagamento', models.DateField()),
                ('media_consumo', models.FloatField()),
            ],
        ),
    ]
