# Generated by Django 3.2.9 on 2021-11-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta',
            options={'verbose_name': 'Conta de Luz'},
        ),
        migrations.AlterModelTable(
            name='conta',
            table='contas',
        ),
    ]
