# Generated by Django 3.2.9 on 2021-12-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20211115_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='kw',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='conta',
            name='numero_leitura',
            field=models.PositiveIntegerField(),
        ),
    ]
